#!/bin/bash

PATH="/bin:/usr/bin"

function usage(){
    echo "Just specify the NetID and provide the password and you're good to go"
}

QUIET=0
VERBOSE=0
PASSWD="-W"
while getopts “hqvp:f:” OPTION
do
    case $OPTION in
        h)
        usage
        exit 1
        ;;
        q)
        QUIET=1
        ;;
        v)
        VERBOSE=1
        ;;
        p)
        PASSWD="-w $OPTARG"
        ;;
        f)
        PASSWD="-y $OPTARG"
        ;;
        ?)
        usage
        exit
        ;;
    esac
done

user=$1

#Default to current user
if [ -z $user ]; then
    user=$USER
fi

if [ $VERBOSE -eq 1 ]; then
    exec /usr/bin/ldapsearch -LLL -H ldaps://ldap.rutgers.edu:636 -x -D "uid=$USER,ou=people,dc=rutgers,dc=edu" $PASSWD -b "ou=people,dc=rutgers,dc=edu" "(uid=$USER)" rulinkRutgersEduStudentGpaCum
fi

if [ $QUIET -eq 0 ]; then
    echo "Enter LDAP password for $user: "
fi

gpa=`/usr/bin/ldapsearch -LLL -H ldaps://ldap.rutgers.edu:636 -x -D "uid=$USER,ou=people,dc=rutgers,dc=edu" $PASSWD -b "ou=people,dc=rutgers,dc=edu" "(uid=$USER)" rulinkRutgersEduStudentGpaCum 2>&1 | grep rulink | awk -F: '{ print $2}' | awk -F' ' '{ print $1 }'`

if [ $? -eq 0 ]; then
    if [ $QUIET -eq 0 ]; then
        echo "$user : $gpa"
    else
        echo $gpa
    fi
    exit 0
else
    if [ $QUIET -eq 0 ]; then
        echo "Wrong username/password for user $user" 2>&1
    fi
    exit 1
fi
